name: SkyblockVault
main: git.kmark43.skyblockvault.SkyblockVaultPlugin
version: "0.2"
api-version: "1.13"
author: kmark43

commands:
    vault:
        usage: /vault
        description: Opens your vault
        permission: skyblockvault.openvault
permissions:
    skyblockvault.openvault:
        default: op